{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c6aa106d-b1f6-41ed-8037-d4bb4490eb6e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " ---------------------------------------\n",
      "1. Enter the number and information of student(s).\n",
      "2. Enter the number and information of course(s).\n",
      "3. Enter mark for student(s).\n",
      "4. List of student(s).\n",
      "5. List of course(s).\n",
      "6. Show student(s) mark.\n",
      "7. Sort student by GPA.\n",
      "8. End\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter the next step:  1\n"
     ]
    }
   ],
   "source": [
    "import math\n",
    "\n",
    "class Student:\n",
    "    def __init__(self, student_id, name, dob):\n",
    "        self.id = student_id\n",
    "        self.name = name\n",
    "        self.dob = dob\n",
    "        self.courses = []\n",
    "\n",
    "    def input_marks(self, course_id, marks, credits):\n",
    "        rounded_marks = math.floor(marks)\n",
    "        self.courses.append({\"course_id\": course_id, \"marks\": rounded_marks, \"credits\": credits})\n",
    "\n",
    "    def calculate_gpa(self):\n",
    "        total_credits = 0\n",
    "        total_mark = 0\n",
    "\n",
    "        for course in self.courses:\n",
    "            total_credits += (course[\"credits\"])\n",
    "            total_mark += course[\"marks\"]\n",
    "\n",
    "        if total_credits == 0:\n",
    "            return 0\n",
    "        return total_mark / total_credits\n",
    "\n",
    "    def display_info(self):\n",
    "        print(f\"Student ID: {self.id} - Name: {self.name} - GPA: {self.calculate_gpa()}\")\n",
    "\n",
    "class Course:\n",
    "    def __init__(self, course_id, name, credits):\n",
    "        self.id = course_id\n",
    "        self.name = name\n",
    "        self.credits = credits\n",
    "\n",
    "students = []\n",
    "courses = []\n",
    "\n",
    "def number_of_students():\n",
    "    return int(input(\"Enter the number of student(s): \"))\n",
    "\n",
    "def number_of_courses():\n",
    "    return int(input(\"Enter the number of course(s): \"))\n",
    "\n",
    "def check_student_number(students):\n",
    "    if len(students) == 0:\n",
    "        print(\"There is no student yet!\")\n",
    "        return False\n",
    "    else:\n",
    "        return True\n",
    "\n",
    "def check_course_number(courses):\n",
    "    if len(courses) == 0:\n",
    "        print(\"There is no course yet!\")\n",
    "        return False\n",
    "    else:\n",
    "        return True\n",
    "\n",
    "def select_course(courses):\n",
    "    print(\"Select a course: \")\n",
    "    list_courses(courses)\n",
    "    course_id = input(\"Enter course ID: \")\n",
    "\n",
    "    for course in courses:\n",
    "        if course.id == course_id:\n",
    "            return course\n",
    "\n",
    "def list_students(students):\n",
    "    print(\"List of students: \")\n",
    "    for student in students:\n",
    "        student.display_info()\n",
    "\n",
    "def list_courses(courses):\n",
    "    print(\"List of courses: \")\n",
    "    for course in courses:\n",
    "        print(f\"Course ID: {course.id} - Name: {course.name} - Credits: {course.credits}\")\n",
    "\n",
    "def show_student_marks(student, selected_course):\n",
    "    if check_student_number(students) and check_course_number(courses):\n",
    "        print(f\"Mark for {selected_course.name} - Course ID: {selected_course.id} - Credits: {selected_course.credits}\")\n",
    "        for _ in student.courses:\n",
    "            if _['course_id'] == selected_course.id:\n",
    "                print(f\"Student ID: {student.id} - Name: {student.name} - Marks: {_['marks']}\")\n",
    "                return\n",
    "        print(f\"No marks found for {selected_course.name}\")\n",
    "\n",
    "def sort_students_by_gpa(students):\n",
    "    return sorted(students, key=lambda x: x.calculate_gpa(), reverse=True)\n",
    "def list_of_choice():\n",
    "    print(\" ---------------------------------------\")\n",
    "    print(\"1. Enter the number and information of student(s).\")\n",
    "    print(\"2. Enter the number and information of course(s).\")\n",
    "    print(\"3. Enter mark for student(s).\")\n",
    "    print(\"4. List of student(s).\")\n",
    "    print(\"5. List of course(s).\")\n",
    "    print(\"6. Show student(s) mark.\")\n",
    "    print(\"7. Sort student by GPA.\")\n",
    "    print(\"8. End\")\n",
    "def select_choice():\n",
    "    exit_program = False\n",
    "    while not exit_program:\n",
    "        list_of_choice()\n",
    "        choice = int(input(\"Enter the next step: \"))\n",
    "\n",
    "        if choice == 1:\n",
    "            number_student = number_of_students()\n",
    "            for _ in range(number_student):\n",
    "                student_id = input(\"Enter student id: \")\n",
    "                student_name = input(\"Enter student name: \")\n",
    "                student_dob = input(\"Enter student dob: \")\n",
    "                student = Student(student_id, student_name, student_dob)\n",
    "                students.append(student)\n",
    "\n",
    "        elif choice == 2:\n",
    "            number_courses = number_of_courses()\n",
    "            for _ in range(number_courses):\n",
    "                course_id = input(\"Enter course id: \")\n",
    "                course_name = input(\"Enter course name: \")\n",
    "                course_credits = int(input(\"Enter course credits: \"))\n",
    "                course = Course(course_id, course_name, course_credits)\n",
    "                courses.append(course)\n",
    "\n",
    "        elif choice == 3:\n",
    "            if check_student_number(students) and check_course_number(courses):\n",
    "                selected_course = select_course(courses)\n",
    "                if selected_course:\n",
    "                    for student in students:\n",
    "                        marks = float(input(f\"Enter the mark for {selected_course.name} of the student {student.name}: \"))\n",
    "                        credits = selected_course.credits\n",
    "                        student.input_marks(selected_course.id, marks, credits)\n",
    "\n",
    "        elif choice == 4:\n",
    "            if check_student_number(students):\n",
    "                list_students(students)\n",
    "\n",
    "        elif choice == 5:\n",
    "            if check_course_number(courses):\n",
    "                list_courses(courses)\n",
    "\n",
    "        elif choice == 6:\n",
    "            if check_student_number(students) and check_course_number(courses):\n",
    "                selected_course = select_course(courses)\n",
    "                if selected_course:\n",
    "                    for student in students:\n",
    "                        show_student_marks(student, selected_course)\n",
    "\n",
    "        elif choice == 7:\n",
    "            if check_student_number(students):\n",
    "                sorted_students = sort_students_by_gpa(students)\n",
    "                print(\"Students sorted by GPA:\")\n",
    "                list_students(sorted_students)\n",
    "\n",
    "        elif choice == 8:\n",
    "            print(\"Program ended.\")\n",
    "            exit_program = True  # Set the flag to exit the loop\n",
    "\n",
    "        else:\n",
    "            print(\"Invalid choice. Please try again.\")\n",
    "def main():\n",
    "    select_choice()\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()          \n",
    "            "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7d94803b-3522-4129-84da-770420a261ae",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2061b41a-47f6-4f91-a00c-4b6cd34248c7",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ee145822-dbac-46e6-adb1-43786dd81a67",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "35237a16-d032-4805-8d41-09c3cf20c04b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2eba1ef3-dd6d-46fe-987c-4600c23f2838",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "12dbfb8c-8c3e-486d-92a1-a1afa7faacce",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
